### ISSUE TITLE
New Package "Shruggie"

### ISSUE THREAD

**Issue by spikex** [federico-terzi/espanso-hub#1]
I'm a fan of ¯\_(ツ)_/¯ the [Shruggie emoticon](https://emojipedia.org/shrug/) but it's not easily typed. This package inserts it when you type `:shrug`.

Package Repo: https://github.com/spikex/shruggie

**Comment by federico-terzi** [comment]
Hi @spikex,
Thank you very much for your contribution! I've added your package to the espanso hub.
There is just a small problem, in this line:
https://github.com/spikex/shruggie/blob/cf2682d87764b4fb4c2ed9b6c2502421c2ea968b/shruggie/0.1.0/package.yml#L8

You should escape the backslash for it to work correctly:
```
    replace: "¯\\_(ツ)_/¯"
```

Regards

**Comment by spikex** [comment]
Hey, Federico, I’ve added the missing backslash.

**Comment by federico-terzi** [comment]
Thanks! You're now the creator of the first community package on the hub :)
https://hub.espanso.org/packages/shruggie/

By the way, I installed your package and I'm now a happy user ¯\_(ツ)_/¯
