### ISSUE TITLE
Package proposal: HTML utilities package

### ISSUE THREAD

**Issue by woodenbell** [federico-terzi/espanso-hub#10]
This awesome tool inspired me to create a package with shortcuts to several common HTML5 tags, I'd like to request it to be added as a package. Here's the [link](https://github.com/woodenbell/html-utils-package).

**Comment by federico-terzi** [comment]
Hey @woodenbell,
Thank you for your help, your package seems very useful indeed!
Here you go: [https://hub.espanso.org/packages/html-utils-package/](https://hub.espanso.org/packages/html-utils-package/)

Cheers :)
