### ISSUE TITLE
New Package: Arrows

### ISSUE THREAD

**Issue by j6k4m8** [federico-terzi/espanso-hub#13]
This package adds support for → arrows ← and a few dashes. See the README for a full list of symbols.

https://github.com/j6k4m8/espanso-arrows

**Comment by federico-terzi** [comment]
Thanks again for your help @j6k4m8, here we go: https://hub.espanso.org/packages/arrows/

**Comment by j6k4m8** [comment]
Awesome!! Thank you for including :)
