### ISSUE TITLE
New Package: Pinyin

### ISSUE THREAD

**Issue by j6k4m8** [federico-terzi/espanso-hub#14]
This package adds easy access to typing the Pinyin Mandarin Romanization vowels (mnemonic explained in the readme below):

https://github.com/j6k4m8/espanso-pinyin

**Comment by federico-terzi** [comment]
Hey @j6k4m8,

Your package is now on the hub: https://hub.espanso.org/packages/pinyin/

Thanks for your help :)

**Comment by j6k4m8** [comment]
xièxie :)
