### ISSUE TITLE
new package request

### ISSUE THREAD

**Issue by femtocept** [federico-terzi/espanso-hub#16]
I hope you are well.

I love the digraph mnemonics from vim so I made a package for them. It covers a ton of ground and might attract vim users to espanso.

https://github.com/femtocept/espanso-package-example

Please let me know if something is improper, I tried to follow your docs. This is my first time contributing to a github project so this is exciting.

BM

**Comment by federico-terzi** [comment]
Hey @femtoceptt,

Thank you very much for your contribution, it seems like a neat package indeed!
Here we go: https://hub.espanso.org/packages/vim-digraphs/

Cheers :)
