### ISSUE TITLE
Kaimoji package

### ISSUE THREAD

**Issue by pard68** [federico-terzi/espanso-hub#21]
I've created this package with a far more extensive selection of kaimojis than either shruggie or fliptable. My thought was that instead of making a single package for ech kaimoji just make one package for all the popular ones, like the emoji package.
URL: https://github.com/pard68/kaimoji

**Comment by federico-terzi** [comment]
Sorry for the late reply, I've been going through a super busy period!
Here is the package: https://hub.espanso.org/packages/kaimoji/

Cheers :)
