### ISSUE TITLE
German Postleitzahlen (postal codes) package

### ISSUE THREAD

**Issue by cyberfux** [federico-terzi/espanso-hub#22]
https://github.com/cyberfux/german-plz

**Comment by federico-terzi** [comment]
Your package is now live :) 
```
espanso install german-plz --external
```

**Comment by cyberfux** [comment]
Cool, but i don't know why it's not working...

Sascha F. Kraeling
Lange Str. 39
39264 Bornum
Tel +4939248-943421
Mobil +4915225240070
Twitter @cyberfux
Facebook http://www.facebook.com/cyberfux


Am Di., 9. Juni 2020 um 20:45 Uhr schrieb Federico Terzi <
notifications@github.com>:

**Comment by federico-terzi** [comment]
What error are you getting? I tried and it installs correctly on my machine

**Comment by cyberfux** [comment]
No error - it just don't work (sometimes).

Btw. where is the package installed to (linux)? Trying to figure something
out...

Sascha F. Kraeling
Lange Str. 39
39264 Bornum
Tel +4939248-943421
Mobil +4915225240070
Twitter @cyberfux
Facebook http://www.facebook.com/cyberfux


Am Mi., 10. Juni 2020 um 08:35 Uhr schrieb Federico Terzi <
notifications@github.com>:
