### ISSUE TITLE
Q: Why does espanso sometimes don't react to the trigger?

### ISSUE THREAD

**Issue by cyberfux** [federico-terzi/espanso-hub#23]
Sometimes there is no response to a trigger while on another time it works fine (using my postal code package),

Could it be that over 59k trigger are too much?

**Comment by federico-terzi** [comment]
Hey,

This shouldn't happen even with many matches. Have you found some steps to reproduce this issue?
If that's the case, could you open an issue on the main tracker: https://github.com/federico-terzi/espanso/issues

Thanks for your help :)

**Comment by cyberfux** [comment]
Hi!

Nope sorry, there is no recognizable pattern.

I first thought it would happen because of double entries (there are some,
would be nice if one gets to choose like in PhraseExpress) but it happens
also sometimes on single entries and then again not on doubles...

It could be that it's my machine as i have the entries in default.yml at
the moment till the package is approved - perhaps you could check it on
your machine?

Thanks!

Sascha F. Kraeling
Lange Str. 39
39264 Bornum
Tel +4939248-943421
Mobil +4915225240070
Twitter @cyberfux
Facebook http://www.facebook.com/cyberfux


Am Di., 9. Juni 2020 um 09:29 Uhr schrieb Federico Terzi <
notifications@github.com>:

**Comment by cyberfux** [comment]
Hoi!

I did a screencast, as you can see: No rhyme - no reason...
 vokoscreen-2020-06-09_11-41-08.gif
<https://drive.google.com/file/d/1LTS4oJ1DAC8jZRoTD22zL2I09YA6_7fs/view?usp=drive_web>

Sascha F. Kraeling
Lange Str. 39
39264 Bornum
Tel +4939248-943421
Mobil +4915225240070
Twitter @cyberfux
Facebook http://www.facebook.com/cyberfux


Am Di., 9. Juni 2020 um 09:29 Uhr schrieb Federico Terzi <
notifications@github.com>:

**Comment by federico-terzi** [comment]
Not sure what could be causing it. If possible could you open an issue on the main issue tracker? Because here it's hard for me to keep track of them.

Cheers :)
