### ISSUE TITLE
german-plz

### ISSUE THREAD

**Issue by cyberfux** [federico-terzi/espanso-hub#26]
Streamlined version 1.0 down from 3.2MiB to 458.1 kiB
https://github.com/cyberfux/german-plz

**Comment by federico-terzi** [comment]
Could you please change version of the package form "1.0" to "0.1.1"?

**Comment by cyberfux** [comment]
Done, i think...

Sascha F. Kraeling
Lange Str. 39
39264 Bornum
Tel +4939248-943421
Mobil +4915225240070
Twitter @cyberfux
Facebook http://www.facebook.com/cyberfux


Am Do., 11. Juni 2020 um 19:23 Uhr schrieb Federico Terzi <
notifications@github.com>:

**Comment by federico-terzi** [comment]
Should be good to go now :)
