### ISSUE TITLE
New Package: Gitmoji support

### ISSUE THREAD

**Issue by Lyokolux** [federico-terzi/espanso-hub#29]
Hi @federico-terzi  !
I made a package for the [Gitmojis project](https://gitmoji.carloscuesta.me/) at https://github.com/Lyokolux/espanso-gitmojis.
This package is different of the `all-emojis` as it strictly follow standardized gitmoji (with underscore + it supports only the ones that are displayed on the website).
I think the two projects can help each other 👊

**Comment by federico-terzi** [comment]
Here you go: https://hub.espanso.org/packages/gitmojis/

Thanks for the help :)

**Comment by Lyokolux** [comment]
Whoops I have forgotten some typos in the README.md 😅 

Here is the updated README : https://raw.githubusercontent.com/Lyokolux/espanso-gitmojis/master/README.md

Thanks for adding it !

**Comment by federico-terzi** [comment]
Should be good now :)
