### ISSUE TITLE
package proposal: Greek Letters

### ISSUE THREAD

**Issue by exergonic** [federico-terzi/espanso-hub#3]
Thank you for making espanso!  I discovered it through the DistroTube channel on Youtube. 
 
New package:
https://github.com/exergonic/espanso-package-greek-letters

I've put together a small package of Greek upper and lowercase letters. All uppercase and lowercase Greek letters are included. They are expanded from the keypresses <kbd>:g?</kbd> where <kbd>?</kbd> is a single upper or lowercase English letter.  

I create this because typing Greek letters has been problematic for me in the past. The `compose` key doesn't propagate into all programs, and changing my keyboard layout via my DE's tools is cumbersome. Text expansion is the easiest method for me.

**Comment by federico-terzi** [comment]
Hey @exergonic,
Thank you for your help! I uploaded your package to the hub: https://hub.espanso.org/packages/greek-letters/

By the way, I started developing espanso for the same reason, as I found difficult to type Italian accented letters, so I understand your pain :)

Cheers
