### ISSUE TITLE
New package - wttr

### ISSUE THREAD

**Issue by bradyjoslin** [federico-terzi/espanso-hub#32]
https://github.com/bradyjoslin/espanso-package-wttr

An espanso package for getting the weather from [Igor Chubin's](https://github.com/chubin) console-oriented weather service [wttr.in](https://wttr.in).

## Usage

Available replacement examples:

| replacement           | sample output                    | description                           |
| --------------------- | -------------------------------- | ------------------------------------- |
| `:wttrin`             | Spring, United States: ⛅️ +80°F | Current location's current weather    |
| `:moonphase`          | 🌕                               | Current phase of the moon             |
| `:wttrat/{location}/` | dallas: ☀️ +88°F                 | Current weather in specified location.  Separate words with `+` instead of spaces. |

**Comment by federico-terzi** [comment]
Here is the last one :) https://hub.espanso.org/packages/wttr/
