### ISSUE TITLE
New package - cht

### ISSUE THREAD

**Issue by bradyjoslin** [federico-terzi/espanso-hub#33]
https://github.com/bradyjoslin/espanso-package-cht

An espanso package for getting code snippets from [Igor Chubin's](https://github.com/chubin) console-oriented cheat sheet service [cht.sh](https://cht.sh).

![chtjs](https://user-images.githubusercontent.com/13108888/89214486-81eaae00-d58c-11ea-9a80-4c8b7e09fa08.gif)

## Usage

Available replacements:

| replacement      | description                 |
| ---------------- | --------------------------- |
| `:cht/{query}/`  | Code only, no comments.     |
| `:vcht/{query}/` | Verbose. Code and comments. |

**Comment by federico-terzi** [comment]
Here we go :) https://hub.espanso.org/packages/cht/
