### ISSUE TITLE
New package - sharewifi

### ISSUE THREAD

**Issue by bradyjoslin** [federico-terzi/espanso-hub#34]
https://github.com/bradyjoslin/espanso-package-sharewifi

An espanso package for quickly sharing Wi-Fi passwords and connection details on macOS using [sharewifi](https://github.com/bradyjoslin/sharewifi). Generates QR codes that auto-configure iOS and Android devices.

![sharewifi](https://user-images.githubusercontent.com/13108888/89233871-2c27fd00-d5b0-11ea-99ac-339bed5a1d2a.gif)

Available replacements:

| replacement    | description                                                  |
| -------------- | ------------------------------------------------------------ |
| `:sharewifi`   | Prints Wi-Fi password.                                       |
| `:qrsharewifi` | Prints Wi-Fi Network config QR Code for Android and iOS 11+. |
| `:vsharewifi`  | Verbose output. Prints SSID and Password.                    |

Requires [sharewifi](https://github.com/bradyjoslin/sharewifi).

**Comment by federico-terzi** [comment]
Ready! https://hub.espanso.org/packages/sharewifi/
