### ISSUE TITLE
Sharewifi page on hub

### ISSUE THREAD

**Issue by bradyjoslin** [federico-terzi/espanso-hub#35]
Noticed a few things related to the [sharewifi page](https://hub.espanso.org/packages/sharewifi/) on espanso hub:

1) The gif is a broken image.  Is there something I can do on my end to help fix?  (I noticed the gif for the [cht package](https://hub.espanso.org/packages/cht/) worked.)
2) The title on the posting on hub is "sharewifi Package - 0.1.0" - would be better if I removed the word "Package".  I'm inferring that's pulling from the package title in [this markdown file](https://github.com/bradyjoslin/espanso-package-sharewifi/blob/master/sharewifi/README.md)?  Hoping I can update `package_title` without it having bad side-effects?

**Comment by federico-terzi** [comment]
Hey @bradyjoslin,
My bad, should be good to go now: https://hub.espanso.org/packages/sharewifi/
Cheers :)
