### ISSUE TITLE
French Accents Package

### ISSUE THREAD

**Issue by ottopiramuthu** [federico-terzi/espanso-hub#4]
I made a package for French accents which closely mirrors `german-accents` on Espanso Hu`b:
- [package repository](https://github.com/ottopiramuthu/espanso-package-example)

Please let me know if I need to fix anything.

**Comment by federico-terzi** [comment]
Hey @ottopiramuthu,
Your package is now live! [https://hub.espanso.org/packages/french-accents/](https://hub.espanso.org/packages/french-accents/)

Thanks for your help :)
