### ISSUE TITLE
html-utils-package has been updated to 0.1.1

### ISSUE THREAD

**Issue by woodenbell** [federico-terzi/espanso-hub#40]
Hi,
I'd like to ask for a new README to be included and the package files to be updated, because `html-utils-package` has changed to version `0.1.1`.
The repository is [here](https://github.com/woodenbell/html-utils-package).

Thanks

**Comment by federico-terzi** [comment]
Updated! https://hub.espanso.org/packages/html-utils-package/
Cheers :)
