### ISSUE TITLE
New Package - LaTeX symbols

### ISSUE THREAD

**Issue by zoenglinghou** [federico-terzi/espanso-hub#41]
https://github.com/zoenglinghou/espanso-latex

This package expands latex commands to symbols. e.g.
`\alpha\` to `α`

**Comment by federico-terzi** [comment]
Hey,
Sorry for the late reply!
The package is now online! https://hub.espanso.org/packages/espanso-latex/
Thanks a lot for your help, and happy new year :)

**Comment by zoenglinghou** [comment]
Happy new year to you too!
