### ISSUE TITLE
New Package - Obsidian in Colour

### ISSUE THREAD

**Issue by KuSi833** [federico-terzi/espanso-hub#42]
url: https://github.com/KuSi833/espanso-obsidian-in-colour

For this to work the user would need to download the python script as well.
I'm unsure whether that happens automatically as well when the `espanso install obsidian-in-colour` is run.

**Comment by federico-terzi** [comment]
Hey,
Sorry for the late reply!
The package is now online! https://hub.espanso.org/packages/obsidian-in-colour/

> For this to work the user would need to download the python script as well.

Yes, the user will need to download the script by itself (as of now, it's not possible to bundle the script automatically)

Thanks a lot for your help, and happy new year :)
