### ISSUE TITLE
New Package - What the Commit

### ISSUE THREAD

**Issue by omrilotan** [federico-terzi/espanso-hub#43]
url: https://github.com/omrilotan/espanso-package-wtc

---

Espanso package that gets a hilarious random commit message.

![](https://user-images.githubusercontent.com/516342/99454223-cda04800-292e-11eb-9034-e5c625ee0073.gif)

Powered by [What The Commit](https://whatthecommit.com/).

**Comment by federico-terzi** [comment]
Hey,
Sorry for the late reply!
The package is now online! https://hub.espanso.org/packages/wtc/
Thanks a lot for your help, and happy new year :)
