### ISSUE TITLE
New Package — Blackboard Characters

### ISSUE THREAD

**Issue by j6k4m8** [federico-terzi/espanso-hub#44]
This package adds "blackboard," double-struck characters, such as `ℂ` or `ℤ` for all latin [A..Za..z].

Note that unlike other packages, this abbreviation prefix specifically _does not_ interfere with LaTeX shortcuts (i.e. you don't need to turn this off when writing LaTeX).

https://github.com/j6k4m8/espanso-blackboard

**Comment by federico-terzi** [comment]
Hey,
Sorry for the late reply!
The package is now online! https://hub.espanso.org/packages/blackboardletters/
Thanks a lot for your help, and happy new year :)

**Comment by j6k4m8** [comment]
Thank you!! Happy new year :)
