### ISSUE TITLE
New Package — Quantum Unicode

### ISSUE THREAD

**Issue by j6k4m8** [federico-terzi/espanso-hub#45]
Common unicode expansions for quantum mechanics, notation, and computation

URL: https://github.com/j6k4m8/espanso-quantum

| Abbreviation | Expansion |
|--------------|-----------|
|<kbd>\\\\to</kbd> | → |
|<kbd>\\\\bbN</kbd> | ℕ |
|<kbd>\\\\bbR</kbd> | ℝ |
|<kbd>\\\\pi</kbd> | π |
|<kbd>\\\\bbB</kbd> | 𝔹 |
|<kbd>\\\\cdot</kbd> | ⋅ |
|<kbd>\\\\theta</kbd> | θ |
|<kbd>\\\\psi</kbd> | ψ |
|<kbd>\\\\lambda</kbd> | λ |
|<kbd>\\\\neg</kbd> | ¬ |
|<kbd>\\\\times</kbd> | × |
|<kbd>\\\\pm</kbd> | ± |
|<kbd>\\\\bb1</kbd> | 𝟙 |
|<kbd>\\\\bra</kbd> | ⟨ |
|<kbd>\\\\ket</kbd> | ⟩ |

**Comment by federico-terzi** [comment]
Thanks again for your help!
The package is online: https://hub.espanso.org/packages/quantum/
