### ISSUE TITLE
FR: Link to package source from the hub page

### ISSUE THREAD

**Issue by n8henrie** [federico-terzi/espanso-hub#58]
Hello -- 

I've been using espanso happily for several months but just recently decided to try a package. 

I went to install https://hub.espanso.org/packages/excel-package/ but was surprised to find no meaningful information on the page, just says `Useful Excel formulas`.

That's not a big deal, I can just look through the source code... however, I was then surprised to find no links for me to be able to find more information! 

Looking at the source file: https://github.com/federico-terzi/espanso-hub/blob/master/_packages/excel-package.md, t looks like `package_original_repo` is right there and should be trivial to expose so the end users can peruse the source before deciding that a package is worth installing.

**Comment by federico-terzi** [comment]
Hey @n8henrie,

Sorry for the late reply! You're absolutely right. We are currently rebuilding the hub from scratch, and source view+links to the repo will be supported there: https://github.com/espanso/hub/issues/2

Thank you for the help!

Cheers :)
