### ISSUE TITLE
Package proposal: Greek letters with triggers based on letter name

### ISSUE THREAD

**Issue by Su-Well** [federico-terzi/espanso-hub#8]
I really liked @exergonic's idea of expansion of greek letters. However, I'm used to the MS word expansion which is based on letter names. Therefore, I forked @exergonic's package and changed the triggers.

I realize there is some redundancy here, so I would understand if the proposal is declined. It's possible that a different approach (instead of another package) would be better. For instance, if you could define multiple triggers in the same package, and expose a user setting to switch between "modes", where one mode activates one set of triggers, and another mode activates another set of triggers.

In any case, here's the repo link: https://github.com/Su-Well/espanso-package-greek-letters

**Comment by federico-terzi** [comment]
Hey @Su-Well,
Every alternative is appreciated! your package is now live [https://hub.espanso.org/packages/greek-letters-alt/](https://hub.espanso.org/packages/greek-letters-alt/)

Thanks for your help :)
