### ISSUE TITLE
Package proposal: Mac symbols

### ISSUE THREAD

**Issue by lifesign** [federico-terzi/espanso-hub#9]
Thank you for this awesome project! I discovered it through the awesome-rust repo.

I create this for display common mac symbols

https://github.com/lifesign/espanso-mac-symbols

**Comment by federico-terzi** [comment]
Hey @lifesign,
I'm really sorry for the late reply, I've had a terrible week.
Thank you very much for your help! your package is now live: https://hub.espanso.org/packages/mac-symbols/

Cheers :)

**Comment by lifesign** [comment]
thx~
